---
- name: Install mongodb package
  apt:
    name: mongodb
    state: present
    update_cache: true
  tags: install

- name: Enable mongodb service
  systemd:
    name: mongodb
    enabled: yes
  tags: install
